### ISSUE TITLE
IllegalArgumentException when parsing IPv6 address with scope_id

### ISSUE THREAD

**Issue by GoogleCodeExporter** [janvanbesien/java-ipv6#15]
```
What steps will reproduce the problem?
Use IPv6Address.fromInetAddress() with an address containing a scope_id throws 
java.lang.IllegalArgumentException.

For example:
InetSocketAddress sa = ...
IPv6Address.fromInetAddress(sa.getAddress())

java.lang.IllegalArgumentException: can not parse 
[fe80:0:0:0:1234:1234:1234:1234%11]
	at com.googlecode.ipv6.IPv6Address.tryParseStringArrayIntoLongArray(IPv6Address.java:94)
	at com.googlecode.ipv6.IPv6Address.fromString(IPv6Address.java:80)
	at com.googlecode.ipv6.IPv6Address.fromInetAddress(IPv6Address.java:109)
```

Original issue reported on code.google.com by `rene.fic...@gmail.com` on 30 Oct 2014 at 1:39

**Comment by janvanbesien** [comment]
Released as part of 0.16
