### ISSUE TITLE
IPv6AddressRange.toSubnets fails with min and max inputs

### ISSUE THREAD

**Issue by p-clark** [janvanbesien/java-ipv6#18]
Thank you for the useful library.  I believe I found an issue when dealing with the entirety of the ipv6 address space.  My expectation is that the following code would output
::/0

However, it is failing with an exception.

    IPv6AddressRange.fromFirstAndLast(IPv6Address.fromBigInteger(BigInteger.ZERO),
        IPv6Address.fromBigInteger(new BigInteger("340282366920938463463374607431768211455")))
        .toSubnets().forEachRemaining(i -> {
          System.out.println(i.toString());
        });

Fails with:
java.lang.IllegalArgumentException: can only set bits in the interval [0, 127]
	at com.googlecode.ipv6.IPv6Address.setBit(IPv6Address.java:335)
	at com.googlecode.ipv6.IPv6AddressRange$IPv6AddressRangeAsSubnetsIterator.next(IPv6AddressRange.java:279)
	at com.googlecode.ipv6.IPv6AddressRange$IPv6AddressRangeAsSubnetsIterator.next(IPv6AddressRange.java:263)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.fm.util.common.ip.IPAddressTest.testParsing(IPAddressTest.java:30)

**Comment by janvanbesien** [comment]
Thanks for the report, I can confirm this to be a bug indeed. I'll look into it.

**Comment by janvanbesien** [comment]
Fixed on master.

**Comment by p-clark** [comment]
Would you be able to release this library into maven central?  The last release is 0.16 from a few years ago, however there have been a number of fixes and improvements.
